 (function () {
	document.querySelector("#container").innerHTML =     ` 
      <div class="inner">

        <header>
          <h1>-frontcamp-introduction-to-ecmascript-2015-v2</h1>
          <h2>first task for Front Camp</h2>
        </header>

        <section id="downloads" class="clearfix">
          <a href="https://github.com/VittalQSC/-FrontCamp-Introduction-to-ECMAScript-2015-v2/zipball/master" id="download-zip" class="button"><span>Download .zip</span></a>
          <a href="https://github.com/VittalQSC/-FrontCamp-Introduction-to-ECMAScript-2015-v2/tarball/master" id="download-tar-gz" class="button"><span>Download .tar.gz</span></a>
          <a href="https://github.com/VittalQSC/-FrontCamp-Introduction-to-ECMAScript-2015-v2" id="view-on-github" class="button"><span>View on GitHub</span></a>
        </section>

        <hr>

        <section id="main_content">

        </section>

        <footer>
          -frontcamp-introduction-to-ecmascript-2015-v2 is maintained by <a href="https://github.com/VittalQSC">VittalQSC</a><br>
          This page was generated by <a href="https://pages.github.com">GitHub Pages</a>. Tactile theme by <a href="https://twitter.com/jasonlong">Jason Long</a>.
        </footer>

        
      </div>
    `; 
 })()